# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logowanie_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Logowanie(object):
    def setupUi(self, Logowanie):
        Logowanie.setObjectName("Logowanie")
        Logowanie.resize(483, 125)
        self.formLayout = QtWidgets.QFormLayout(Logowanie)
        self.formLayout.setObjectName("formLayout")
        self.logowanieTekst_label = QtWidgets.QLabel(Logowanie)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.logowanieTekst_label.setFont(font)
        self.logowanieTekst_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logowanieTekst_label.setObjectName("logowanieTekst_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.logowanieTekst_label)
        self.login_label = QtWidgets.QLabel(Logowanie)
        self.login_label.setObjectName("login_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.login_label)
        self.login_edit = QtWidgets.QLineEdit(Logowanie)
        self.login_edit.setObjectName("login_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.login_edit)
        self.haslo_label = QtWidgets.QLabel(Logowanie)
        self.haslo_label.setObjectName("haslo_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.haslo_label)
        self.haslo_edit = QtWidgets.QLineEdit(Logowanie)
        self.haslo_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.haslo_edit.setObjectName("haslo_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.haslo_edit)
        self.zatwierdz_button = QtWidgets.QPushButton(Logowanie)
        self.zatwierdz_button.setObjectName("zatwierdz_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.zatwierdz_button)

        self.retranslateUi(Logowanie)
        QtCore.QMetaObject.connectSlotsByName(Logowanie)

    def retranslateUi(self, Logowanie):
        _translate = QtCore.QCoreApplication.translate
        Logowanie.setWindowTitle(_translate("Logowanie", "Form"))
        self.logowanieTekst_label.setText(_translate("Logowanie", "Logowanie do systemu ECD"))
        self.login_label.setText(_translate("Logowanie", "Login"))
        self.haslo_label.setText(_translate("Logowanie", "Haslo"))
        self.zatwierdz_button.setText(_translate("Logowanie", "Zatwierdź"))
